apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: nginx-ns
spec:
  replicas: 1
  selector:
    # matchlabels: same as template->labels!
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        # same as matchlabels!
        app: nginx-app
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp-pod
    type: front-end
  name: nginx2
  namespace: nginx-ns
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-ns
spec:
  ports:
  - targetPort: 80
    nodePort: 30080
    port: 80
  selector:
    app: myapp-pod
    type: front-end
  type: NodePort
---
